spring:
  application:
    name: backend
  cloud:
    gcp:
      project-id: mindful-rhythm-426908-a5

app:
  jwt:
    secret: ${JWT_SECRET}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  expense-categories:
    - Allowance
    - Food & Drinks
    - Groceries
    - Health & Medical
    - Holidays & Events
    - Housing
    - Life & Entertainment
    - Others
    - Pets, animals
    - Shopping
    - Sports & Fitness
    - Technology & Communication
    - Transportation
