spring:
  application:
    name: backend
  cloud:
    gcp:
      project-id: mindful-rhythm-426908-a5

app:
  jwt:
    secret: ${JWT_SECRET}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  expense-categories:
    - Allowance
    - Car Loan
    - Car Maintenance
    - Food & Drinks
    - Fuel
    - Groceries
    - Health & Medical
    - Holidays & Events
    - Housing
    - Incident/Emergencies
    - Life & Entertainment
    - Others
    - Parking
    - Pets, animals
    - Ride-Hailing
    - Shopping
    - Sports & Fitness
    - Technology & Communication
    - Toll

migration:
  backfill-transportation-category-split:
    enabled: true
